dusk-network/plonk

src/commitment_scheme/kzg10/key.rs, src/constraint_system/standard/composer.rs, src/fft/polynomial.rs
Since we do not use Polynomial long division, we can remove it for a simpler method which contains our use case.
Closes #128
=> Switch Polynomial Long Division for Ruffini

src/cs/composer.rs
While I was coding the gadgets, I realized there's an error on the implementation of `add` and `mul` functions. 
- They were not evaluating correctly the value `w_o` since they were just adding or multiplying the `w_l` and `w_r` instead of also operating them with the selector poly values like now.
- It was also not possible to scale the output value since `q_o` selector poly term was not being counted on the `w_o` computation. 
This has also been fixed with the following modif:
```rust
// Previously, whatever subtraction, or scaling value would fail:
let o = self.eval(&l) + &self.eval(&r)
// This is the propper way of computing the correct `w_o` val:
let o = ((q_l * &self.eval(&l)) + &(q_r * &self.eval(&r)) + &pi + &q_c)  *&-q_c;
```
Note that atm, we need to use `-Fr::one()` for the …
=> [zexe_branch] Fix `add` and `mul`  to evaluate `w_o` correct

Cargo.lock, src/commitment_scheme/kzg10/key.rs, src/constraint_system/standard/proof.rs
Use the newer and faster var_base_msm taken from `zexe` and implemented in our Bls12_381 fork.
Benchmarks can be checked in #138
=> Use new msm_var_base impl of Bls12_381

src/constraint_system/standard/linearisation_poly.rs, src/constraint_system/standard/proof.rs, src/fft/domain.rs, src/fft/polynomial.rs, src/permutation/grand_product_lineariser.rs, src/permutation/grand_product_quotient.rs, src/permutation/permutation.rs
Closes #111 and fixes some docs nitpicks.
This also forces all of the `Scalar` sent as params to functions to be `&Scalar` so we don't force the copy always.
Enables also the usage of `par_iter` in places where it was not being used.
=> Fix references usage

src/commitment_scheme/kzg10/errors.rs, src/commitment_scheme/kzg10/key.rs, src/commitment_scheme/kzg10/mod.rs, src/commitment_scheme/kzg10/srs.rs, src/constraint_system/standard/composer.rs, src/fft/polynomial.rs, src/util.rs
- Removes any inaccuracies in the documentation and cleans up all comments.
- Completes all TODOs and XXXs
-  Uses one pairing when checking the opening proof for a single polynomial
- Cleans up all test functions to be more readable with helper functions
A step towards #121
=> Cleans up Commitment Scheme Module

.travis.yml
Allow builds with `#![feature(external_doc)]` to fail for `stable` and `beta` channels
=> Update travis to allow nightly doc builds

Cargo.toml, benchmarks/plonk_benchmarks.rs, src/commitment_scheme/kzg10/key.rs, src/commitment_scheme/kzg10/mod.rs, src/commitment_scheme/kzg10/srs.rs, src/constraint_system/standard/linearisation_poly.rs, src/constraint_system/standard/preprocessed_circuit.rs, src/constraint_system/standard/proof.rs, src/constraint_system/widget/arithmetic.rs, src/constraint_system/widget/logic.rs, src/constraint_system/widget/mod.rs, src/constraint_system/widget/permutation.rs, src/constraint_system/widget/range.rs, src/fft/domain.rs, src/fft/evaluations.rs, src/fft/polynomial.rs, src/lib.rs
- Adds serde impl for `PreProcessedCircuit` and it's components. Closes #170
- Adds serde impl for `Proof` and it's components. Closes #171
- Adds serde impl for `SRS` and it's components. Closes #127 
The serde implementations are behind a `serde` feature which comes enabled by default in `default-features`. See `Cargo.toml`. On this way, the `serde` implementations are optional to be or not used by the end-user.
This Pr also adds `PartialEq` & `Eq` derivations for almost all of  the structs of the crate since those were needed in order to do the serde impl testing.
- Memory -> `SerializedProof` with `bincode` = 972bytes.
- Performance ->
```
Proof Serde/Deserialization                                                                             
time:   [6.5842 ms 6.6738 ms 6.7583 ms] …
```
=> Add serde support for crate's data structures

src/constraint_system/standard/composer.rs, src/permutation/permutation.rs
This removes the responsibility of padding from the permutation module, to the prover. 
Was merged in #192 from #193
=> Pad witness in Prover

.travis.yml, CHANGELOG.md, Cargo.toml, benchmarks/plonk_benchmarks.rs, examples/0_setup_srs.rs, examples/1_compose_prove_verify.rs, examples/2_gadget_orientation.rs, examples/3_0_setup_for_gadgets.rs, examples/3_1_final_gadget_orientation.rs, src/commitment_scheme/kzg10/errors.rs, src/commitment_scheme/kzg10/key.rs, src/commitment_scheme/kzg10/srs.rs, src/constraint_system/composer.rs, src/constraint_system/cs_errors.rs, src/constraint_system/mod.rs, src/fft/domain.rs, src/fft/fft_errors.rs, src/fft/mod.rs, src/fft/polynomial.rs, src/proof_system/mod.rs, src/proof_system/proof.rs, src/proof_system/proof_system_errors.rs, src/proof_system/quotient_poly.rs
- Custom errors for the following modules:
1. Composer
2. fft
3. proof_system
4. commitment_scheme (refactored)
- All of the errors are converted to `failure::Error` which makes easier to manage the error handling since we just have one General type of error with different implementations per module. 
- Having this general Error type allows us to propagate custom error types for each module across the library without any compatibility problem. 
- It also provides the user a way to dissect the error on it's lib when implements plonk as a dependency.
- Create a prelude file that not only contains the important data structures but also the whole collection of errors that we provide with the lib.
=> Implement propper Error handling for the plonk library

src/proof_system/linearisation_poly.rs, src/proof_system/proof.rs, src/proof_system/prover.rs, src/proof_system/quotient_poly.rs, src/proof_system/widget/arithmetic.rs, src/proof_system/widget/logic.rs, src/proof_system/widget/range.rs
This PR diverges from the reference implementation.
Each identity has it's own challenge, to which we can take powers of, to separate sub identities.
I believe this way is safer  and ensures that no identity contains a power of alpha that was used in previous identity. Additionally, it means that alpha challenge has one purposes, while the separation challenges also have one purpose. This should increase code readability. 
Closes #148
=> Add identity separation challenge to each identity

CHANGELOG.md, examples/1_compose_prove_verify.rs, examples/2_gadget_orientation.rs, examples/3_0_setup_for_gadgets.rs, examples/3_1_final_gadget_orientation.rs, src/constraint_system/mod.rs, src/fft/fft_errors.rs, src/lib.rs, src/permutation/mod.rs, src/prelude.rs
- Re-exports `dusk-bls12_38::Scalar`.
- Exports the needed data structures needed to work with plonk as well as the plonk errors inside of a module.
Closes #227 and one of the points of the tracking issue: #237
=> Add prelude file to plonk

Cargo.toml, src/constraint_system/logic.rs, src/lib.rs
As mentioned in #251 there was a problem with the `assert`
statements used in the "front-end" check of the PLONK program
memmory.
This was caused by a bit_num parameter set to less bits than the
actual number bit-size.
Therefore, the assert was checking the final value of the resulting
wire agains the original number provided on each input wire instead
of the value clamped to the correct ammount of bits.
Closes #251 
We also now use `dusk-bls12_381 v0.1.2`, the new version of bls is published in crates.io
=> Fix logic_constraint assertion bug

Cargo.toml, src/lib.rs
Is a way easier to work with bls and jubjub libraries if they
are exported by plonk instead of importing and managing the versions
on our app where we have plonk as dep.
Closes #256
=> Export curve crates in plonk

CHANGELOG.md, src/constraint_system/composer.rs
We needed before to create a witness and then constrain it to a
constant on every circuit we had.
This was time consuming and makes the code less readable since these
kind of constraints should already be performed by the Composer.
- Added the `add_constant_witness` method to the `StandardComposer`
impl block.
Adds the passed `BlsScalar` to the Constraint System as a
witness value and constraints it to be equal to the value that
was sent.
This makes easier to work with Public Inputs, since they can just be
used as witnesses constrained to a fixed value.
Closes #264
=> Implement a method for constraint-to-const witnes

src/proof_system/proof.rs
Since now the verification is done through the `Verifier` abstraction,
we no longer need to expose publicly the `verify()` method of the
`Proof` object. Indeed, we can simply change it to `pub(crate)` and
let the `Verifier` method call it.
Closes #263
=> Remove pub visibility of Proof::verify()

CHANGELOG.md, Cargo.toml, src/constraint_system/ecc/mod.rs
Some key expansion strategy may depend on the coordinates of the point,
like the case in Poseidon Cipher.
This way, the user need to have the ability to read the generated
coordinates.
=> ECC Point should have its attributes exposed

CHANGELOG.md, Cargo.toml, src/commitment_scheme/kzg10/errors.rs, src/commitment_scheme/kzg10/key.rs, src/commitment_scheme/kzg10/srs.rs, src/constraint_system/cs_errors.rs, src/constraint_system/helper.rs, src/fft/domain.rs, src/fft/fft_errors.rs, src/lib.rs, src/prelude.rs, src/proof_system/preprocess.rs, src/proof_system/proof.rs, src/proof_system/proof_system_errors.rs, src/proof_system/prover.rs, src/proof_system/quotient_poly.rs, src/proof_system/verifier.rs
Replaced the types & macro invocations used previously by
failure crate by the ones required by `anyhow` & `thiserror`.
- Refactored the `XXXErrors` enum to use `thiserror` as the
`derive` macro provider.
- Use `anyhow::{Result, Error}; as main types returned by plonk.
=> Migrate from `failure` to `anyhow + thiserror` for error support.

CHANGELOG.md, src/constraint_system/composer.rs
Previously this required to send both, a `Scalar` and
a `Variable` with the same shared value.
By modifying the function signature, this will generate
a witness `Variable` constrained to be equal to
a constant `Scalar` which is sent to the function.
Closes #282
=> Update `add_witness_to_circuit_description` fn sig

CHANGELOG.md, Cargo.toml
- `Anyhow` & `thiserror` for error handling support.
- Serialisation methods for the crate public structures &
`serde` support.
- dusk-jubjub version updated to 0.3.6
- `failure` for error support since has been deprecated.
=> Version 0.2.7

CHANGELOG.md, Cargo.toml, src/prelude.rs
- This PR also adds `CircuitBuilder` traits inside of `prelude` so they're exported with the new version.
Bumps this crate to `0.2.10`
=> Bump to v0.2.10

CHANGELOG.md, src/circuit_builder.rs, src/prelude.rs
The `Circuit` trait was not flexible enough for some of the circuits that we were implementing in issues like https://github.com/dusk-network/dusk-blindbid/issues/65.
Therefore, we needed more flexibility from the `CircuitInputs` perspective as well as a way to set the `PublicInputs` value correctly.
This PR introduces the following changes:
- Removed `CircuitInputs` structure and use the struct that implements `Circuit` as the container to store the inputs.
- Use `gadget()` fn in the verification definition to avoid bugs that deal to short Opening Keys.
- Make `build_pi()` return a `Result<T>` since now the inputs might not be charged inside the structure.
This leads to make possible the implementation of more complex circuits such as the BlindBid Circuit, so at least we know that the …
=> Circuit trait refactoring to make it usable & efficient

CHANGELOG.md, Cargo.toml, src/circuit_builder.rs
The API was not flexible enough and it was forcing us
to repeat a lot of code.
- Trait now comes with build_pi, gen_proof, compile & verify_proof
fn's already implemented.
- It forces the user to implement the getters and setters for the PI
vector storage.
- It carries the circuit size already hardcored in it.
We've also defined the method pos() for PublicInput in order to get
quick access to them.
=> Improve Circuit trait API and usability

CHANGELOG.md, Cargo.toml, src/circuit_builder.rs
On the cases where we have variable-size circuits,
we need a way to use different trim_sizes for our Circuit
instance. With the previous API this was not possible.
Therefore, the method `set_trim_size` has been added.
=> Trim size as param

CHANGELOG.md, Cargo.toml
Ready to merge once https://github.com/dusk-network/jubjub/pull/52 gets merged.
Adds the jubjub version that includes `Canon` derived for `ExtendedPoint`.
=> Add flag-featured Canon-derived ecc libs usage.

CHANGELOG.md, src/constraint_system/logic.rs
Remove uncessary `match` branch for `var_c` [#414](https://github.com/dusk-network/plonk/issues/414)
=> rm uncessary match branch mentioned in #414

docs/notes-prove-verify.md
The docs file had a faulty hyperlink. This is because within files it is not possible to connect to mod level markdowns.
This is now removed.
This closes #415
=> Remove hyperlink from SNARK docs.

src/proof_system/proof.rs
In order to impl the propper `BadLenght` trait & others we need to set
the associated error for the `Serializable` trait impl for `Proof` as
`dusk_bytes::Error` and take profit of the conversion with `?` to convert
the error into a `plonk::Error` when needed.
Resolves: #447
=> Fix Error type used for Serializable impl Proof

CHANGELOG.md, src/error.rs, src/proof_system/proof.rs
- Remove `Canon` impl for `Proof`.
- Make the `std::Error` impl behind `std` flag.
Resolves: #450
=> Fix canon feature related compilation errors

README.md, src/circuit.rs
As discussed with the core team, this would enable features like
circuit versioning with techniqes like:
> You could generate the ID by hashing the `gadget()` fn code
in a proc_macro with something like Blake3.
Resolves: #417
=> Implement ID associated const for Circuit trait

src/constraint_system/composer.rs
There's no other way to enable easy tests for the
users that develop gadgets that is not implement
the Gadget as if it was a Circuit by itself which is
nonsensical.
So this changes the fn visibility to `pub` for
`StandardComposer::construct_dense_pi_vec`.
Resolves: #461
=> Change dense PI construction fn in Composer

src/commitment_scheme/kzg10/srs.rs
Make `PublicParameters::trim` a public method
avaliable for backwards testing compatibility
reasons.
Resolves: #460
=> Change trim() visibility to pub

CHANGELOG.md, Cargo.toml, src/commitment_scheme/kzg10/srs.rs, src/constraint_system/composer.rs
Resolves #464 
- Change `PublicParameters::trim` visibility to `pub`. [#460](https://github.com/dusk-network/plonk/issues/460)
- Change `StandardComposer::construct_dense_pi_vec` visibility to `pub`.[#461](https://github.com/dusk-network/plonk/issues/461)
=> Release version 0.6.1

CHANGELOG.md, src/circuit.rs
The Public Input positions and the VerifierKey are two items related
logically but not in terms of code. Therefore, it would be nice to also
link them in the code.
By adding `VerifierData` the verifier can always have linked
the pi_positions and the keys of the same circuit linked
with a struct that is serializable.
Resolved: #466
=> Add `VerifierData` struct 

CHANGELOG.md, src/commitment_scheme/kzg10/key.rs, src/commitment_scheme/kzg10/mod.rs, src/proof_system/proof.rs
Implement From G1Affine and G1Projective for Commitment.
Resolves: #433
=> Impl From trait for Commitment

CHANGELOG.md, Cargo.toml, src/circuit.rs
Resolves: #494
Do we need to derive `Canon` for any data structure that doesn't derive it now such as `Proof`? So that we don't need to treat it as `Vec<u8>`?
Would be nice to know and address on a follow-up PR.
=> Update to canonical 0.6

CHANGELOG.md, Cargo.toml, src/commitment_scheme/kzg10/proof.rs, src/fft/domain.rs, src/proof_system/proof.rs, src/proof_system/quotient_poly.rs
Adds back `rayon` under `std` feature just for the `quotient_poly` module
and just for a few lines which do not make the code harder to mantain or
less readable, but provide a boost in the performance of a 25%~30%.
Resolves: #512
=> Fix proving performance regressions

CHANGELOG.md, Cargo.toml, src/circuit.rs, src/commitment_scheme/kzg10/proof.rs, src/commitment_scheme/kzg10/srs.rs, src/fft/domain.rs, src/proof_system/proof.rs, src/proof_system/quotient_poly.rs
There are times as for example in the `Circuit::verify_proof` fn
where we just need to retrive the `OpeningKey` from a
`PublicParameters` instance without any need of trimming them
ie. trim the `CommitKey`.
Therefore, this PR adds an alternative way to obtain the `CommitKey`
and the `OpeningKey` and implements the second one in the circuit
module.
Resolves: #510
=> Add getters to avoid trimming for OpeningKey obtention

src/constraint_system/ecc/scalar_mul/variable_base.rs
This was a leftover from the latest ECC API refactor and it should
have been on that way to be inline with the fixed_base impl.
Resolves: #522
=> Add variable_base_scalar_mul as Composer associated method

src/permutation/permutation.rs, src/plookup/multiset.rs, src/proof_system/linearisation_poly.rs, src/proof_system/proof.rs, src/proof_system/prover.rs, src/proof_system/quotient_poly.rs, src/proof_system/widget/lookup/proverkey.rs, src/proof_system/widget/lookup/verifierkey.rs
The plookup permutation product argument is changed to use an alternating split for h1 and h2, and the prover and verifier algorithms have been modified to match.
=> Make alternating

CHANGELOG.md, README.md, src/circuit.rs, src/constraint_system/arithmetic.rs, src/constraint_system/boolean.rs, src/constraint_system/composer.rs, src/constraint_system/ecc/curve_addition/fixed_base_gate.rs, src/constraint_system/ecc/curve_addition/variable_base_gate.rs, src/constraint_system/ecc/mod.rs, src/constraint_system/ecc/scalar_mul/fixed_base.rs, src/constraint_system/ecc/scalar_mul/variable_base.rs, src/constraint_system/helper.rs, src/constraint_system/logic.rs, src/constraint_system/mod.rs, src/constraint_system/range.rs, src/lib.rs, src/permutation/permutation.rs, src/prelude.rs, src/proof_system/preprocess.rs, src/proof_system/proof.rs, src/proof_system/prover.rs, src/proof_system/verifier.rs
- Change `StandardComposer` to `TurboComposer`. 
Resolves: #288
=> Turbo composer renaming

CHANGELOG.md, src/permutation/permutation.rs, src/proof_system/preprocess.rs, src/proof_system/prover.rs
Remove old perm-computation fns to test module
Some of the functions were only being used to test that indeed the other
permutation implementations that are much more performant work as
expected and provide correct results.
Therefore, it makes no sense to have the "backup"/"testing" functions
anywhere else that is not a testing module.
Resolves: #515
=> Perm module cleanup

CHANGELOG.md, Cargo.toml, README.md, benches/plonk.rs
Results obtained with: Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
```
Prove 2^5 = 32 constraints                                                                           
time:   [18.471 ms 18.564 ms 18.677 ms]
Prove 2^6 = 64 constraints                                                                           
time:   [24.155 ms 24.291 ms 24.539 ms]
Found 1 outliers among 10 measurements (10.00%)
1 (10.00%) high severe
Prove 2^7 = 128 constraints                                                                           
time:   [38.306 ms 38.598 ms 38.874 ms]
Prove 2^8 = 256 constraints                                                                           
time:   [60.509 ms 62.260 ms 64.296 ms]
Found 1 outliers among 10 measurements (10.00%)
1 (10.00%) high mild
Prove 2^9 = 512 …
```
=> Add benchmarks to the crate

CHANGELOG.md, README.md, src/circuit.rs, src/constraint_system/arithmetic.rs, src/constraint_system/boolean.rs, src/constraint_system/composer.rs, src/constraint_system/ecc/curve_addition/fixed_base_gate.rs, src/constraint_system/ecc/curve_addition/variable_base_gate.rs, src/constraint_system/ecc/mod.rs, src/constraint_system/ecc/scalar_mul/fixed_base.rs, src/constraint_system/ecc/scalar_mul/variable_base.rs, src/constraint_system/logic.rs, src/constraint_system/mod.rs, src/constraint_system/range.rs, src/constraint_system/variable.rs, src/permutation/permutation.rs, src/prelude.rs, src/proof_system/preprocess.rs
Add `AllocatedScalar` as part of PLONK's external API
Now instead of mangling with `Variable`s, users will use
`AllocatedScalar` instead which includes a reference to the
Scalar a `Variable` references.
- Make all pub fn's get and return `AllocatedScalar` in their
signatures.
Now the `Variable` type is something more internal to the crate and
there should not be any uses for it outside of the crate internals.
This is required in order to be able to externalized some gadgets added into this lib in `modularized_plookup` branch which should have never been included here and need this API change in order to be a thing outside of the lib itself.
Resolves: #565
=> AllocatedScalar refactor

CHANGELOG.md, Cargo.toml, src/circuit.rs
`PublicInputValue` implements `From<JubJubAffine>`.
Since `JubJubExtended` implements `Into<JubJubAffine>`, the
implementation of `From<JubJubExtended>` for `PublicInputValue` is
trivial.
This will save the consumers of the API some additional and unnecessary
conversions.
Resolves #573
=> Add `From` extended point to `PublicInputValue`

src/constraint_system/composer.rs
Adds missing dummy constraints in test and removes the `#[ignore]` resulting in a passing test.
=> Add missing dummy constraints in test

src/circuit.rs, src/constraint_system/composer.rs
Addresses issue #590
`test_plonkup_proof` was pretty interesting. Firstly `max_degree` and `truncated_degree` were set far too small, secondly the circuits definitions were set differently for the `Prover` and for the `Verifier`.
=> Fix ignored tests

.cargo/config.toml, CHANGELOG.md
Previously LaTeX wasn't rendered in the official documentation of
our crate. With this change a custom header is inserted in the
html-files for the documentation, allowing LaTeX generated code
to be rendered with KaTeX.
As a side-effect of this change, `cargo doc` needs to be run with
the `--no-deps` flag:
```
$ cargo doc --no-deps
```
Resolves: #567
=> Add support for rendering LaTeX in the docs

CHANGELOG.md, src/constraint_system/composer.rs
We have available `append_public_point` for points, but we don't have
such method for witnesses. These will avoid unnecessary constraints for
the users.
It is desirable to have API consistency - the methods to append points
should reflect the ones to append public inputs.
Resolves #654
=> Add `append_public_witness` to `TurboComposer`

CHANGELOG.md, benches/plonk.rs, src/circuit.rs, src/commitment_scheme/kzg10/srs.rs
Adding the blinding factors required some extra elements for the SRS: `+1` per each wire (we have 4 wires), plus `+2` for the permutation polynomial. There was a bug in the original commit, that caused errors when compiling some circuits. We fix it here by doing:
- In `srs.rs`, the `max_degree` in `setup()` is updated: `+ 6`
- In `srs.rs`, the truncated degree used in `trim()` is updated: `+ 6`.
- The `+ 6` used in `circuit.rs` has been removed as it is no longer required.
- We reverted a change in `benches/plonk.rs`, no longer required.
=> Fix error with the max degree of the SRS

CHANGELOG.md, Cargo.toml, Makefile
With this PR the math finally should render on docs.rs. 
There is also the make rule `make docs-local` added that opens the docs from the current branch locally.
Resolves: #567
=> Fix math latex rendering on docs.rs

Cargo.toml
The version needs to be bumped so we can cascade the `rkyv`related changes to upstream crates
=> Bump version to `0.12.0-rc.0`

CHANGELOG.md, Cargo.toml, src/circuit.rs, src/commitment_scheme/kzg10/commitment.rs, src/commitment_scheme/kzg10/key.rs, src/commitment_scheme/kzg10/srs.rs, src/fft/domain.rs, src/fft/evaluations.rs, src/fft/polynomial.rs, src/proof_system/linearization_poly.rs, src/proof_system/proof.rs, src/proof_system/widget.rs, src/proof_system/widget/arithmetic/proverkey.rs, src/proof_system/widget/arithmetic/verifierkey.rs, src/proof_system/widget/ecc/curve_addition/proverkey.rs, src/proof_system/widget/ecc/curve_addition/verifierkey.rs, src/proof_system/widget/ecc/scalar_mul/fixed_base/proverkey.rs, src/proof_system/widget/ecc/scalar_mul/fixed_base/verifierkey.rs, src/proof_system/widget/logic/proverkey.rs, src/proof_system/widget/logic/verifierkey.rs, src/proof_system/widget/permutation/proverkey.rs, src/proof_system/widget/permutation/verifierkey.rs, src/proof_system/widget/range/proverkey.rs, src/proof_system/widget/range/verifierkey.rs, src/util.rs
This is required to ensure the structures can pass through the VM argument border.
This required some manual implementations due to internal types being exposed otherwise with the `derive`.
=> Add `CheckBytes` implementations

CHANGELOG.md, Cargo.toml, src/proof_system/widget.rs
This errant manual implementation of `CheckBytes` was using the `rkyv` `validation` feature which bring in `std`. This is not desirable for smart contract development, and would break compilation of the crate with only the `alloc` and `rkyv-impl` features enabled.
=> Remove `rkyv` validation feature

CHANGELOG.md, Cargo.toml
- Remove manual implementation of `CheckBytes` for `ArchivedProverKey`. This
is necessary since `rkyv/validation` was required as a bound.
=> Bump version to `0.13.1`

CHANGELOG.md, src/composer.rs, tests/composer.rs, tests/ecc.rs
This change also required to change the negation of the constant in `append_equal_constant`.
Tests added as well.
Resolves #728
=> Fix negation of coordinates in `assert_equal_public_point`

tests/assert_equal.rs, tests/boolean.rs, tests/common/mod.rs, tests/ecc.rs, tests/select_bls.rs, tests/select_point.rs
This issue covers:
- add helper functions:
- `setup`
- `check_satisfied_circuit`
- `check_unsatisfied_circuit`
- refactor tests:
- `assert_equal_point`
- `assert_equal_public_point`
- `component_mul_point`
- `component_add_point`
- `component_mul_generator`
- `component_boolean`
- `component_select`
- `component_select_one`
- `component_select_zero`
- `component_select_point`
- `component_select_identity`
Resolves #731
=> Refactor integration tests

tests/append_gate.rs, tests/assert_point.rs, tests/assert_scalar.rs, tests/boolean.rs, tests/common/mod.rs, tests/ecc.rs, tests/logic.rs, tests/select_bls.rs, tests/select_point.rs
=> Refactor and add tests for logic component

CHANGELOG.md, src/composer.rs, tests/decomposition.rs
Also add a simple example as to how the scalar will be decomposed.
Resolves #738, resolves #704
=> Add and refactor tests for decomposition component

CHANGELOG.md, Cargo.toml
- Add and restructure tests for `assert_equal_point` [#725]
- Add and restructure tests for `assert_equal_public_point` [#727]
- Add and restructure tests for `append_gate` [#737]
- Add and restructure tests for `assert_equal` and `assert_equal_constant` [#733]
- Add and restructure tests for logic component [#734]
- Add and restructure tests for range component [#735]
- Add and restructure tests for boolean and select components [#731]
- Add tests for `gate_add` and `gate_mul` [#736]
- Add and restructure tests for `component_decomposition` [#738]
- Remove `bit_iterator` macro [#632]
- Fix negation of public input values when using `composer.append_public` [#717]
- Fix `assert_equal_point` method [#720]
- Fix negation of constant in `append_equal_constant` [#728]
- Fix negation of public …
=> Release v0.14.0

CHANGELOG.md, Cargo.toml, benches/plonk.rs, src/composer.rs, src/composer/compiler.rs, src/composer/compiler/compress.rs, src/composer/compiler/compress/hades.rs, src/composer/prover.rs, src/composer/verifier.rs, src/constraint_system/constraint.rs, src/constraint_system/witness.rs, src/error.rs, tests/common/mod.rs, tests/composer.rs
This commit introduces `Compiler::compress` and `Compiler::decompress`, two functions that will create a compressed representation of a circuit that can be used to generate prover and verifier keys.
The compression strategy takes advantage of the fact that circuit representations are sparse; meaning, most of the scalars are zeroes. We also have a higher incidence of `1` and `-1`, so any value that is equivalent to a `i8` is compressed into a single byte, instead of the regular `32` bytes of a bls12-381.
This will result in expressive gains in terms of storage. For instance, a `2^12` circuit can be compressed into roughly 100Kb.
=> feat: add `compress` to compiler

CHANGELOG.md, src/composer.rs, src/error.rs, tests/size.rs
This fixes a panic on proof creation when the circuit to prove is larger than in the provers circuit description
=> Add test and fix for panic on prove

src/commitment_scheme/kzg10/key.rs, src/fft/polynomial.rs, src/proof_system/quotient_poly.rs, src/proof_system/widget.rs
Related to https://github.com/dusk-network/plonk/issues/174.
- make the `Vec` inside of the `Polynomial` struct private
- implement `IntoIterator` for `Polynomial`
- implement `iter()` for `Polynomial`
- propagate the effects of previous changes by removing direct access to the wrapped `Vec`
=> Implement Iter and IntoIter for Polynomial

CHANGELOG.md, README.md, benches/plonk.rs, src/composer.rs, tests/append_gate.rs, tests/assert_point.rs, tests/assert_scalar.rs, tests/boolean.rs, tests/common/mod.rs, tests/composer.rs, tests/decomposition.rs, tests/ecc.rs, tests/gate_add_mul.rs, tests/logic.rs, tests/range.rs, tests/select_bls.rs, tests/select_point.rs
=> Fix tests panic in debug

CHANGELOG.md, src/composer.rs, src/composer/builder.rs, src/composer/circuit.rs, src/composer/compiler.rs, src/composer/compiler/compress.rs, src/debugger.rs, src/runtime.rs, tests/composer.rs
This change also removes the need to preallocate the circuit builder which in turn removes the need to pass the public parameters when compressing a circuit.
Resolves #767
=> Add `size` method to `Circuit` trait

CHANGELOG.md, Cargo.toml
- Add `size` method to the `Circuit` trait [#767]
- Add `ff` dependency
- Remove `PublicParameters` from parameters for circuit compression [#767]
- Remove `canonical` and `canonical_derive` dependency
- Remove `canon` feature
- update `dusk-bls12_381` dependency to "0.12"
- update `dusk-jubjub` dependency to "0.13"
[0.16.0]: https://github.com/dusk-network/plonk/compare/v0.15.0...v0.16.0
=> Release 0.16.0

CHANGELOG.md, src/commitment_scheme/kzg10/key.rs, src/commitment_scheme/kzg10/srs.rs, src/composer.rs, src/composer/compiler.rs, src/composer/compiler/compress.rs, src/composer/prover.rs, src/fft/evaluations.rs, src/fft/polynomial.rs, src/runtime.rs
=> Fix clippy warnings

CHANGELOG.md, src/composer.rs, src/composer/arithmetization.rs, src/composer/builder.rs, src/composer/compiler.rs, src/composer/compiler/compress.rs, src/composer/prover.rs
close https://github.com/dusk-network/plonk/issues/706
`composer::Polynomial` and `fft::Polynomial` are confusing so renamed `composer::Polynomial` to `Arithmetization`.
I renamed `fft::Polynomial as FftPolynomial ` to `Polynomial` accordingly.
I would appreciate it if you could confirm.
Thank you.
=> rename polynomial to arithmetization

.github/codecov.yml, CHANGELOG.md, src/composer.rs, src/error.rs
=> Add JubJubScalarMalformed error

CHANGELOG.md, Cargo.toml
- Add `JubJubScalarMalformed` error [#784]
- Add blinding factors to the quotient polynomial [#773]
- Update `criterion` dev-dependency to 0.5
- Fix clippy warnings [#774]
- Rename `composer::Polynomial` to `composer::Arithmetization`
- Rename `fft::{Polynomial as FftPolynomial}` to `fft::Polynomial`
[0.17.0]: https://github.com/dusk-network/plonk/compare/v0.16.0...v0.17.0
=> Bump to version 0.17.0

CHANGELOG.md, Cargo.toml
- dusk-bls12_381 -> 0.13
- dusk-jubjub -> 0.14
[0.18.0]: https://github.com/dusk-network/plonk/compare/v0.17.0...v0.18.0
=> Bump to v0.18.0

CHANGELOG.md, src/commitment_scheme/kzg10/key.rs, src/composer/arithmetization.rs, src/composer/builder.rs, src/composer/compiler.rs, src/composer/compiler/compress.rs, src/composer/prover.rs, src/permutation.rs, src/proof_system/linearization_poly.rs, src/proof_system/proof.rs, src/proof_system/quotient_poly.rs, src/proof_system/widget/arithmetic/proverkey.rs, src/proof_system/widget/arithmetic/verifierkey.rs, src/proof_system/widget/ecc/curve_addition/proverkey.rs, src/proof_system/widget/ecc/curve_addition/verifierkey.rs, src/proof_system/widget/ecc/scalar_mul/fixed_base/proverkey.rs, src/proof_system/widget/ecc/scalar_mul/fixed_base/verifierkey.rs, src/proof_system/widget/logic/proverkey.rs, src/proof_system/widget/logic/verifierkey.rs, src/proof_system/widget/permutation/proverkey.rs, src/proof_system/widget/permutation/verifierkey.rs, src/proof_system/widget/range/proverkey.rs, src/proof_system/widget/range/verifierkey.rs, tests/append_gate.rs
=> Fix inconsistent gate ordering

CHANGELOG.md, src/fft/polynomial.rs
=> Fix leading coefficients might be zero

CHANGELOG.md, src/composer.rs, src/error.rs, tests/error_size.rs
=> Improve InvalidCircuitSize error message

CHANGELOG.md, src/lib.rs
=> Hide all modules except prelude

CHANGELOG.md, src/compiler.rs, src/composer.rs, src/composer/circuit.rs, src/composer/compress.rs, tests/composer.rs
=> Improve API for circuit compression

.github/workflows/dusk_ci.yml, Cargo.toml, README.md, examples/circuit.rs, src/fft/domain.rs, tests/common/mod.rs
Also add an example for creating a circuit.
Resolves #346
=> Fix "alloc" feature for tests

CHANGELOG.md, Cargo.toml
- Fix inconsistency in gate ordering of arithmetic verifier key [#797]
- Fix leading coefficients might be zero [#796]
- Fix tests when default features are turned off by placing them behind the `alloc` feature
- Improve InvalidCircuitSize error [#792]
- Hide all modules except 'prelude' [#782]
- Turn `Composer` trait into a struct [#802]
- Rename `Arithmetization` to `Gate` [#802]
- Change internal module structure [#805]:
- Move compiler module to root
- Move prover and verifier modules under compiler
- Move compress module under composer
- Move constraint_system module under composer
- Move permutation module under composer
- Change API for circuit (de-)compression [#804]
- Remove `Builder` struct with introduction of `Composer` struct [#802]
- Remove example from README in favor of an …
=> Release 0.19.0

Cargo.toml
If the examples are excluded, the crate can not be published.
=> Include examples in the release

CHANGELOG.md, rust-toolchain.toml, src/composer/compress/hades.rs
=> Reduce hades constants from 960 to 335

CHANGELOG.md, src/composer/constraint_system/witness.rs
=> Add `Default` trait implementation for `Witness`

CHANGELOG.md, Cargo.toml
- Reduce hades constants count in circuit compression from 960 to 335 [#813]
- Add `Default` trait for `Witness` [#815]
[0.19.1]: https://github.com/dusk-network/plonk/compare/v0.19.0...v0.19.1
=> Bump to v0.19.1

CHANGELOG.md, Cargo.toml, src/composer/constraint_system/witness.rs
=> Add `Zeroize` trait implementation for `Witness`

Cargo.toml
- Add `zeroize` as an optional dependency [#818]
- Add `zeroize` feature [#818]
- Add `Zeroize` trait implementation for `Witness` behind `zeroize` feature [#818]
This rc release outside of the release schedule is needed for being able to open poseidon for audit.
=> Bump to v0.19.2-rc.0

.github/workflows/dusk_ci.yml
=> Update actions checkout and codecov

CHANGELOG.md, README.md, src/proof_system/proof.rs
Resolves: https://github.com/dusk-network/plonk/issues/834
=> Boost verifier
