dusk-network/plonk

src/constraint_system/standard/composer.rs, src/permutation/permutation.rs
=> Moves the responsibility of the witness values to the composer

src/constraint_system/standard/composer.rs, src/constraint_system/standard/linearisation_poly.rs, src/constraint_system/standard/preprocessed_circuit.rs, src/constraint_system/standard/proof.rs, src/constraint_system/standard/quotient_poly.rs
=> Adds width-4 add gate

src/constraint_system/standard/composer.rs
Part of #145 
Adds a width-4 mul gate and cleans up the width-3 gates to use the width-4 gates with d set to zero
=> Adds a width-4 Mul gate

src/bit_iterator.rs, src/constraint_system/standard/composer.rs, src/constraint_system/standard/linearisation_poly.rs, src/constraint_system/standard/preprocessed_circuit.rs, src/constraint_system/standard/proof.rs, src/constraint_system/standard/quotient_poly.rs, src/lib.rs, src/permutation/permutation.rs
=> Adds range constraint gate

src/constraint_system/standard/linearisation_poly.rs, src/constraint_system/standard/proof.rs, src/constraint_system/standard/quotient_poly.rs, src/permutation/grand_product_lineariser.rs, src/permutation/grand_product_quotient.rs
The paper has been updated to start off alpha from alpha^0 , this saves 1 exponentiation.
=> Updates the application of 'alpha' in the quotient polynomial

src/commitment_scheme/kzg10/mod.rs, src/commitment_scheme/kzg10/srs.rs, src/commitment_scheme/mod.rs, src/constraint_system/mod.rs, src/constraint_system/standard/composer.rs, src/constraint_system/standard/mod.rs, src/constraint_system/standard/preprocessed_circuit.rs, src/constraint_system/widget/permutation.rs, src/fft/domain.rs, src/fft/mod.rs, src/fft/polynomial.rs, src/permutation/permutation.rs
This PR is because I went through the code cleaning up the comments for SPAG. 
This PR closes #180
=> Cleaning up comments

.travis.yml, README.md
Temporarily removing code coverage until we can find a way to use it as a heuristic.
Closes #221
=> Removes code coverage 

examples/2_gadget_orientation.rs, examples/3_1_final_gadget_orientation.rs, src/commitment_scheme/kzg10/key.rs, src/commitment_scheme/kzg10/mod.rs, src/commitment_scheme/kzg10/srs.rs, src/constraint_system/composer.rs, src/proof_system/proof.rs, src/proof_system/prover.rs, src/proof_system/verifier.rs
=> Rename `ProverKey` and `VerifierKey` in Commitment scheme

CHANGELOG.md, README.md
=> Update readme WIP sections

.travis.yml, src/commitment_scheme/kzg10/key.rs, src/commitment_scheme/kzg10/mod.rs, src/constraint_system/composer.rs, src/fft/domain.rs, src/proof_system/proof.rs, src/proof_system/quotient_poly.rs, src/proof_system/verifier.rs
=> Replace `TranscriptProtocol` trait with `Transcript`

CHANGELOG.md, Cargo.toml
Bump version to fix JubJubScalar random function. Issue https://github.com/dusk-network/jubjub/issues/25
=> Changed `dusk-jubjub` to`v0.3.5` to fix Fr rnd gen

CHANGELOG.md, Cargo.toml, src/commitment_scheme/kzg10/key.rs, src/commitment_scheme/kzg10/srs.rs, src/constraint_system/composer.rs, src/lib.rs, src/macros.rs, src/proof_system/linearisation_poly.rs, src/proof_system/preprocess.rs, src/proof_system/proof.rs, src/proof_system/widget/arithmetic/verifierkey.rs, src/proof_system/widget/ecc/verifierkey.rs, src/proof_system/widget/logic/verifierkey.rs, src/proof_system/widget/mod.rs, src/proof_system/widget/permutation/verifierkey.rs, src/proof_system/widget/range/verifierkey.rs, src/serialisation.rs
Adds serialisation for ProverKey, VerifierKey, SRS and Proof
=> Add serialisation

Cargo.toml
Updates the following deps:
```toml
dusk-bls12_381 = "0.1.4"
dusk-jubjub = "0.3.7"
```
=> Update JubJub & BLS deps

src/proof_system/mod.rs
=> Export ProverKey & VerifierKey

src/permutation/permutation.rs, src/proof_system/linearisation_poly.rs, src/proof_system/prover.rs, src/proof_system/quotient_poly.rs, src/proof_system/widget/permutation/proverkey.rs
=> Lookup changes

CHANGELOG.md, Cargo.toml, src/bit_iterator.rs, src/circuit_builder.rs, src/commitment_scheme/kzg10/key.rs, src/commitment_scheme/kzg10/srs.rs, src/constraint_system/ecc/scalar_mul/fixed_base/mod.rs, src/constraint_system/ecc/scalar_mul/variable_base/mod.rs, src/constraint_system/logic.rs, src/constraint_system/range.rs, src/fft/polynomial.rs, src/lib.rs, src/proof_system/linearisation_poly.rs, src/proof_system/proof.rs, src/proof_system/widget/mod.rs, src/serialisation.rs, src/transcript.rs, src/util.rs
=> Heavy data structures from unchecked

CHANGELOG.md, Cargo.toml, src/commitment_scheme/kzg10/key.rs, src/commitment_scheme/kzg10/srs.rs
=> Impl #383 - `Clone` for `PublicParameters`

src/permutation/permutation.rs
Remove duplicated code in `test_permutation_format`.
=> rm duplicated code

src/constraint_system/arithmetic.rs, src/permutation/permutation.rs, src/proof_system/preprocess.rs, src/proof_system/widget/arithmetic/proverkey.rs
Fix comment typo in `permutation.rs`.
=> Fix comment typo

src/lib.rs
=> Broken links lint fix

CHANGELOG.md, Cargo.toml, src/constraint_system/composer.rs, src/permutation/permutation.rs
=> Use hashbrown::HashMap instead of collections::HashMap

CHANGELOG.md, src/constraint_system/composer.rs
=> Fix trace_print feature debugger 

CHANGELOG.md, Cargo.toml, src/circuit.rs, src/commitment_scheme/mod.rs, src/constraint_system/composer.rs, src/constraint_system/mod.rs, src/lib.rs, src/proof_system/mod.rs
=> Release 0.7

.github/workflows/dusk_ci.yml
Resolves: #493
This can't be merged until #495 get's merged into `release-0.8`
=> Update CI to test no_std & features better

src/commitment_scheme/kzg10/proof.rs
Since we had some performance issues related to the Proof
verification speed we benchmarked the process and this was
one of the areas where rayon usage could help us to gain a perf
boost.
Resolves: #514
=> Change AggregatedProof flattening to use rayon

.github/workflows/dusk_ci.yml, CHANGELOG.md, Cargo.toml, Makefile, README.md, rust-toolchain, src/constraint_system/arithmetic.rs, src/constraint_system/boolean.rs, src/constraint_system/composer.rs, src/constraint_system/ecc/mod.rs, src/lib.rs, src/proof_system/preprocess.rs
=> Remove `external_doc` and `nightly` feature

src/circuit.rs, src/constraint_system/composer.rs, src/proof_system/linearisation_poly.rs, src/proof_system/proof.rs
Co-authored-by: Eduardo Leegwater Simões <eduardols@protonmail.com>
=> Fix wrong transcript label for lookup challenge

.github/codecov.yml
This config is the default with the addition of disabling github checks
=> Added codecov config

CHANGELOG.md, README.md
Add a disclaimer for library usage
=> Disclaimer

CHANGELOG.md, Cargo.toml
Update to dusk-bls12_381 v0.9
Update to jubjub v0.11
Resolves: #666
=> Update to canonical v0.7 and canonical_derive v0.7

CHANGELOG.md, src/constraint_system/composer.rs
=> Change `append_constant` to accept generic input

CHANGELOG.md, Cargo.toml, src/circuit.rs, src/commitment_scheme.rs, src/commitment_scheme/kzg10.rs, src/commitment_scheme/kzg10/commitment.rs, src/commitment_scheme/kzg10/key.rs, src/commitment_scheme/kzg10/srs.rs, src/fft/domain.rs, src/fft/evaluations.rs, src/fft/polynomial.rs, src/proof_system.rs, src/proof_system/linearization_poly.rs, src/proof_system/proof.rs, src/proof_system/widget.rs, src/proof_system/widget/arithmetic/proverkey.rs, src/proof_system/widget/arithmetic/verifierkey.rs, src/proof_system/widget/ecc/curve_addition/proverkey.rs, src/proof_system/widget/ecc/curve_addition/verifierkey.rs, src/proof_system/widget/ecc/scalar_mul/fixed_base/proverkey.rs, src/proof_system/widget/ecc/scalar_mul/fixed_base/verifierkey.rs, src/proof_system/widget/logic/proverkey.rs, src/proof_system/widget/logic/verifierkey.rs, src/proof_system/widget/permutation/proverkey.rs, src/proof_system/widget/permutation/verifierkey.rs, src/proof_system/widget/range/proverkey.rs, src/proof_system/widget/range/verifierkey.rs
Resolves https://github.com/dusk-network/plonk/issues/697
=> Add `rkyv` implementations behind feature gate

CHANGELOG.md, Cargo.toml
- Add support for `rkyv-impl` under `no_std`
- Update `dusk-cdf` to 0.5 [#709]
=> Bump version to `0.13.0`

CHANGELOG.md, src/composer.rs
=> Fixed negation of public input values

CHANGELOG.md, src/bit_iterator.rs
=> Remove `bit_iterator` macro

src/composer.rs, tests/composer.rs
=> Fix point equality assertion

CHANGELOG.md, tests/append_gate.rs
=> Add tests for `append_gate`

CHANGELOG.md, src/constraint_system/constraint.rs, src/proof_system/widget.rs, tests/append_gate.rs
=> Fix `ProverKey::serialization_size`

src/composer.rs, tests/range.rs
=> Add and refactor tests for range component

CHANGELOG.md, README.md, src/composer.rs, tests/range.rs
=> Fix range gate

CHANGELOG.md, tests/gate_add_mul.rs
=> Add tests for `gate_add` and `gate_mul`

CHANGELOG.md, Cargo.toml
- Add `compress` to compiler [#752]
[0.14.1]: https://github.com/dusk-network/plonk/compare/v0.14.0...v0.14.1
=> Release `0.14.1`

CHANGELOG.md, Cargo.toml
- Fix panic when creating proof for circuit with different circuit size [#760]
- Fix panic when testing in debug mode [#763]
- Remove 'setup' funcion from common test module [#763]
- Change range and logic component to be generic over the const `BIT_PAIRS` [#763]
=> Release v0.15.0

CHANGELOG.md, Cargo.toml
Lock msgpacker version to `0.4.3`
=> bump version to `0.20.2`

CHANGELOG.md, Cargo.toml, src/composer.rs, tests/ecc.rs
=> Add component_sub_point to composer

CHANGELOG.md, Cargo.toml
- Change dependency `dusk-bls12_381` to 0.14
- Change dependency `dusk-jubjub` to 0.15
=> Release `0.21.0`
